### ISSUE TITLE
Add how can we fix migration issue?

### ISSUE THREAD

**Issue by aarivtmk** [mountainkidai/MountainKid-Valley#1]
Hey MountainKid, I come from Mandi and I have seen here a lot of people have been giving up on farming and migrating to cities to have better lifestyle. incase you have any suggestions based on your experience, please add them to this.

Thank you :)

**Comment by mountainkidai** [comment]
Hey Aairv, Thanks for raising the issue, we have started working on this issue. and will be adding the ideas on how can we fix this issue in 7 days.
